// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace NMaven.Plugin.Settings {
    
    
    /// <remarks/>
    public class nmavenSettings {
        
        /// <remarks/>
        public string operatingSystem;
        
        /// <remarks/>
        public string architecture;
        
        /// <remarks/>
        public nmavenSettingsDefaultSetup defaultSetup;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="vendor", IsNullable=false)]
        public nmavenSettingsVendorsVendor[] vendors;
    }
    
    /// <remarks/>
    public class nmavenSettingsDefaultSetup {
        
        /// <remarks/>
        public string vendorName;
        
        /// <remarks/>
        public string vendorVersion;
        
        /// <remarks/>
        public string frameworkVersion;
    }
    
    /// <remarks/>
    public class nmavenSettingsVendorsVendor {
        
        /// <remarks/>
        public string vendorName;
        
        /// <remarks/>
        public string vendorVersion;
        
        /// <remarks/>
        public string isDefault;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="framework", IsNullable=false)]
        public nmavenSettingsVendorsVendorFrameworksFramework[] frameworks;
    }
    
    /// <remarks/>
    public class nmavenSettingsVendorsVendorFrameworksFramework {
        
        /// <remarks/>
        public string frameworkVersion;
        
        /// <remarks/>
        public string installRoot;
        
        /// <remarks/>
        public string sdkInstallRoot;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(ElementName="executablePath", IsNullable=false)]
        public string[] executablePaths;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class NewDataSet {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public nmavenSettings[] nmavenSettings;
    }
}
