//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace NMaven.Model.Setting {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    [System.Xml.Serialization.XmlRootAttribute("settings", Namespace="", IsNullable=false)]
    public partial class Settings {
        
        private string localRepositoryField;
        
        private bool interactiveModeField;
        
        private bool usePluginRegistryField;
        
        private bool offlineField;
        
        private Proxy[] proxiesField;
        
        private Server[] serversField;
        
        private Mirror[] mirrorsField;
        
        private Profile[] profilesField;
        
        private string[] activeProfilesField;
        
        private string[] pluginGroupsField;
        
        public Settings() {
            this.interactiveModeField = true;
            this.usePluginRegistryField = false;
            this.offlineField = false;
        }
        
        /// <remarks/>
        public string localRepository {
            get {
                return this.localRepositoryField;
            }
            set {
                this.localRepositoryField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool interactiveMode {
            get {
                return this.interactiveModeField;
            }
            set {
                this.interactiveModeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool usePluginRegistry {
            get {
                return this.usePluginRegistryField;
            }
            set {
                this.usePluginRegistryField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool offline {
            get {
                return this.offlineField;
            }
            set {
                this.offlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("proxy", IsNullable=false)]
        public Proxy[] proxies {
            get {
                return this.proxiesField;
            }
            set {
                this.proxiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("server", IsNullable=false)]
        public Server[] servers {
            get {
                return this.serversField;
            }
            set {
                this.serversField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mirror", IsNullable=false)]
        public Mirror[] mirrors {
            get {
                return this.mirrorsField;
            }
            set {
                this.mirrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", IsNullable=false)]
        public Profile[] profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("activeProfile", IsNullable=false)]
        public string[] activeProfiles {
            get {
                return this.activeProfilesField;
            }
            set {
                this.activeProfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pluginGroup", IsNullable=false)]
        public string[] pluginGroups {
            get {
                return this.pluginGroupsField;
            }
            set {
                this.pluginGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Proxy {
        
        private bool activeField;
        
        private string protocolField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int portField;
        
        private string hostField;
        
        private string nonProxyHostsField;
        
        private string idField;
        
        public Proxy() {
            this.activeField = false;
            this.protocolField = "http";
            this.portField = 8080;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("http")]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(8080)]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        public string nonProxyHosts {
            get {
                return this.nonProxyHostsField;
            }
            set {
                this.nonProxyHostsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class RepositoryPolicy {
        
        private bool enabledField;
        
        private string updatePolicyField;
        
        private string checksumPolicyField;
        
        public RepositoryPolicy() {
            this.enabledField = true;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        public string updatePolicy {
            get {
                return this.updatePolicyField;
            }
            set {
                this.updatePolicyField = value;
            }
        }
        
        /// <remarks/>
        public string checksumPolicy {
            get {
                return this.checksumPolicyField;
            }
            set {
                this.checksumPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Repository {
        
        private RepositoryPolicy releasesField;
        
        private RepositoryPolicy snapshotsField;
        
        private string idField;
        
        private string nameField;
        
        private string urlField;
        
        private string layoutField;
        
        public Repository() {
            this.layoutField = "default";
        }
        
        /// <remarks/>
        public RepositoryPolicy releases {
            get {
                return this.releasesField;
            }
            set {
                this.releasesField = value;
            }
        }
        
        /// <remarks/>
        public RepositoryPolicy snapshots {
            get {
                return this.snapshotsField;
            }
            set {
                this.snapshotsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("default")]
        public string layout {
            get {
                return this.layoutField;
            }
            set {
                this.layoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class ActivationFile {
        
        private string missingField;
        
        private string existsField;
        
        /// <remarks/>
        public string missing {
            get {
                return this.missingField;
            }
            set {
                this.missingField = value;
            }
        }
        
        /// <remarks/>
        public string exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class ActivationProperty {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class ActivationOS {
        
        private string nameField;
        
        private string familyField;
        
        private string archField;
        
        private string versionField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string arch {
            get {
                return this.archField;
            }
            set {
                this.archField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Activation {
        
        private bool activeByDefaultField;
        
        private string jdkField;
        
        private ActivationOS osField;
        
        private ActivationProperty propertyField;
        
        private ActivationFile fileField;
        
        public Activation() {
            this.activeByDefaultField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool activeByDefault {
            get {
                return this.activeByDefaultField;
            }
            set {
                this.activeByDefaultField = value;
            }
        }
        
        /// <remarks/>
        public string jdk {
            get {
                return this.jdkField;
            }
            set {
                this.jdkField = value;
            }
        }
        
        /// <remarks/>
        public ActivationOS os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public ActivationProperty property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        public ActivationFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Profile {
        
        private Activation activationField;
        
        private ProfileProperties propertiesField;
        
        private Repository[] repositoriesField;
        
        private Repository[] pluginRepositoriesField;
        
        private string idField;
        
        /// <remarks/>
        public Activation activation {
            get {
                return this.activationField;
            }
            set {
                this.activationField = value;
            }
        }
        
        /// <remarks/>
        public ProfileProperties properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("repository", IsNullable=false)]
        public Repository[] repositories {
            get {
                return this.repositoriesField;
            }
            set {
                this.repositoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("pluginRepository", IsNullable=false)]
        public Repository[] pluginRepositories {
            get {
                return this.pluginRepositoriesField;
            }
            set {
                this.pluginRepositoriesField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class ProfileProperties {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Mirror {
        
        private string mirrorOfField;
        
        private string nameField;
        
        private string urlField;
        
        private string idField;
        
        /// <remarks/>
        public string mirrorOf {
            get {
                return this.mirrorOfField;
            }
            set {
                this.mirrorOfField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public partial class Server {
        
        private string usernameField;
        
        private string passwordField;
        
        private string privateKeyField;
        
        private string passphraseField;
        
        private string filePermissionsField;
        
        private string directoryPermissionsField;
        
        private ServerConfiguration configurationField;
        
        private string idField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string privateKey {
            get {
                return this.privateKeyField;
            }
            set {
                this.privateKeyField = value;
            }
        }
        
        /// <remarks/>
        public string passphrase {
            get {
                return this.passphraseField;
            }
            set {
                this.passphraseField = value;
            }
        }
        
        /// <remarks/>
        public string filePermissions {
            get {
                return this.filePermissionsField;
            }
            set {
                this.filePermissionsField = value;
            }
        }
        
        /// <remarks/>
        public string directoryPermissions {
            get {
                return this.directoryPermissionsField;
            }
            set {
                this.directoryPermissionsField = value;
            }
        }
        
        /// <remarks/>
        public ServerConfiguration configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class ServerConfiguration {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
}