using System.Reflection;
using System.Runtime.CompilerServices;
[assembly: AssemblyDescription("")]
[assembly: AssemblyTitle("it0002")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("-it0002")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyConfiguration("")]