//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4959.
// 
#pragma warning disable 1591

namespace TestProject.net.gcomputer.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DilbertSoap", Namespace="http://gcomputer.net/webservices/")]
    public partial class Dilbert : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TodaysDilbertOperationCompleted;
        
        private System.Threading.SendOrPostCallback DailyDilbertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Dilbert() {
            this.Url = global::TestProject.Properties.Settings.Default.TestProject_net_gcomputer_www_Dilbert;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TodaysDilbertCompletedEventHandler TodaysDilbertCompleted;
        
        /// <remarks/>
        public event DailyDilbertCompletedEventHandler DailyDilbertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gcomputer.net/webservices/TodaysDilbert", RequestNamespace="http://gcomputer.net/webservices/", ResponseNamespace="http://gcomputer.net/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TodaysDilbert() {
            object[] results = this.Invoke("TodaysDilbert", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TodaysDilbertAsync() {
            this.TodaysDilbertAsync(null);
        }
        
        /// <remarks/>
        public void TodaysDilbertAsync(object userState) {
            if ((this.TodaysDilbertOperationCompleted == null)) {
                this.TodaysDilbertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTodaysDilbertOperationCompleted);
            }
            this.InvokeAsync("TodaysDilbert", new object[0], this.TodaysDilbertOperationCompleted, userState);
        }
        
        private void OnTodaysDilbertOperationCompleted(object arg) {
            if ((this.TodaysDilbertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TodaysDilbertCompleted(this, new TodaysDilbertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gcomputer.net/webservices/DailyDilbert", RequestNamespace="http://gcomputer.net/webservices/", ResponseNamespace="http://gcomputer.net/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DailyDilbert(System.DateTime ADate) {
            object[] results = this.Invoke("DailyDilbert", new object[] {
                        ADate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DailyDilbertAsync(System.DateTime ADate) {
            this.DailyDilbertAsync(ADate, null);
        }
        
        /// <remarks/>
        public void DailyDilbertAsync(System.DateTime ADate, object userState) {
            if ((this.DailyDilbertOperationCompleted == null)) {
                this.DailyDilbertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDailyDilbertOperationCompleted);
            }
            this.InvokeAsync("DailyDilbert", new object[] {
                        ADate}, this.DailyDilbertOperationCompleted, userState);
        }
        
        private void OnDailyDilbertOperationCompleted(object arg) {
            if ((this.DailyDilbertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DailyDilbertCompleted(this, new DailyDilbertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void TodaysDilbertCompletedEventHandler(object sender, TodaysDilbertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TodaysDilbertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TodaysDilbertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DailyDilbertCompletedEventHandler(object sender, DailyDilbertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DailyDilbertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DailyDilbertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591